$('.nav-tabs')['addClass']('fl')['css']('width', '100%');
$(`${'<link rel="stylesheet" type="text/css" href="">\x0D\x0A\x0D\x0A<link href="https://raw.githack.com/alshanfara/sahar1/main/sahar1.css" rel="stylesheet" type="text/css"  />\x0D\x0A<style>\x0D\x0A\x0D\x0A\x0D\x0A\x0D\x0A\x0D\x0A\x0D\x0Adiv#d0 {width: 100%;-webkit-transform: matrix(1, 0, 0, 1, 47, 0);-moz-transform: matrix(1, 0, 0, 1, 47, 0);-o-transform: matrix(1, 0, 0, 1, 47, 0);-ms-transform: matrix(1, 0, 0, 1, 47, 0);transform: matrix(1, 0, 0, 1, 47, 0);padding: 0px 0px 0px 1px;margin: 1px 0px 0px 0px;}\x0D\x0A\x0D\x0A\x0D\x0A\x0D\x0A.MyColors {\x0D\x0A    position: absolute;\x0D\x0A transform: matrix(1, 0, 0, 1, 85, -1);\x0D\x0A	margin-top: 2px;\x0D\x0A    width: 300px;\x0D\x0A    height: 30px;\x0D\x0A    float: left;\x0D\x0A    background: transparent url(https://nbddd.com/sico/z1eka4nihk10.png) no-repeat scroll right top;\x0D\x0A    text-align: left;\x0D\x0A}\x0D\x0A\x0D\x0A.fr.borderg, .fr.borderg a {\x0D\x0A    font-size: 10px!important;\x0D\x0A    padding: 0 5px!important;\x0D\x0A}\x0D\x0A\x0D\x0A.fr.borderg, .fr.borderg a {\x0D\x0A    margin-top: 4px;\x0D\x0A}\x0D\x0A\x0D\x0A.hmsg {background-color: rgb(235, 241, 255)!important;}\x0D\x0Aa.label.label-primary.fl {display: none}\x0D\x0A#des1 {margin-bottom: 2px;font-family: \'El Messiri\',FontAwesome!important;    background-image: linear-gradient(90deg,#d0d0d0 0,#bababa 10%,#908f8f 51%,#bababa 89%,#d0d0d0 100%);color: #f9f9f9;border-radius: 3px;padding: 4px 0!important;padding-bottom: 3px;}\x0D\x0A\x0D\x0A\x0D\x0A\x0D\x0Aspan.s1.fa.fa-user.label.badgex.label-as-badge.label-success {\x0D\x0Apadding: 0px 3px 2px;\x0D\x0Amargin-right: 5px;\x0D\x0A}\x0D\x0Alabel.label.label-primary.mini.fl{\x0D\x0Apadding: 1px;\x0D\x0Aborder-radius: 15px!important;;\x0D\x0A}\x0D\x0A\x0D\x0A\x0D\x0A\x0D\x0A\x0D\x0Adiv#l1 input#u1,div#l3 button {\x0D\x0A    width: 99%;\x0D\x0A    margin-left: 1px\x0D\x0A}\x0D\x0A\x0D\x0Adiv#l2 button,div#l3 button {\x0D\x0A    border-radius: 24px!important;\x0D\x0A    height: 27px;\x0D\x0A	padding: 0px 5px;\x0D\x0A}\x0D\x0A\x0D\x0Adiv#l1 input#u1 {\x0D\x0A    border-radius: 15px;\x0D\x0A    border: 1px solid #e1e0e0;</style>\x0D\x0A'}`)['insertBefore']('body');
$('.u-pic')['css']('border-radius', '3px');
$('button.btn.btn-primary')['css']('border-radius', '5px');
$('.label-primary')['css']('border-radius', '5px')
$(`<a id="des3" href="" style="transform:matrix(1, 0, 0, 1, 150, 111);border: 1px solid white;border-radius: 0px 15px 0px 0px!important;width:10%;margin:-138px 2px 2px;" class="fl mini fa fa-image btn btn-primary"></a>
<a id="des3" href="" style="border: 1px solid white;transform:matrix(1, 0, 0, 1, 112, 111);border-radius: 0px!important;width:10%;margin:-138px 2px 2px;" class="fl mini fa fa-paint-brush btn btn-primary"></a>
<a id="des3" href="" style="transform:matrix(1, 0, 0, 1, 74, 111);border: 1px solid white;border-radius: 0px!important;width:10%;margin:-138px 2px 2px;" class="fl mini fa fa-star btn btn-primary"></a>
<a id="des3" href="" style="transform:matrix(1, 0, 0, 1, 36, 42);border: 1px solid white;border-radius: 0px!important;width:10%;margin:-69px 2px 2px;" class="fl mini fa fa-phone btn btn-primary"></a>
<a id="des3" href="" style="transform:matrix(1, 0, 0, 1, -2, 7);border: 1px solid white;border-radius: 15px 0px 0px 0px!important;width:10%;margin:-34px 2px 2px;" class="fl mini fa fa fa-heartbeat btn btn-primary"></a>
<a id="des22" style="padding: 2px 0px!important;font-size: 12px !important;border: 1px solid white;border-radius: 0px 0px 0px 0px!important;width:100px;float:right;margin:-68px 2px 2px;transform:matrix(1, 0, 0, 1, 4, 24);" class="label label label-primary " target="_blank" href=""></a>
`).insertBefore('.nav-tabs');
$('<div class=\'fr borderg\' style=\'margin-top: -44px;padding:2px;background-color:white;float:left;\'> ستايل وأرشفة :<a href=\'https://tigerhost.online/\'>تايجر هوست</a></div>')['insertAfter']($('.loginstat'));
$(`<div style="border-radius: 2px 9px 9px 9px!important;width:100%;margin:2px;border: 2px solid #696465;" id="asim33" class="btn btn-primary btn-sm" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample"> صـآحب الموقع</div><div class="collapse" id="collapseExample"><center><div class="well">
<b><font color="#5E706B"> ( عمق) </font> </BR>
`).insertBefore('.nav-tabs');
$(".fa-gear").text("الضبط").css("width","");
